str='python PROGRAMME'
print(str)
x = len(str)
print(x)
x=type(str)
print(x)
x=str.split()
print(x)
x=str.replace('PROGRAMME','learining')
print(x)
x=str.lower()
print(x)
x=str.upper()
print(x)
x=str.capitalize()
print(x)
str="""python
Welcome to python programme"""
print(str)
print(len(str))
x = type(str)
print(x)
x=str.split()
print(x)
x=str.replace('programme','learining')
print(x)
x=str.lower()
print(x)
x=str.upper()
print(x)
x=str.capitalize()
print(x)
str="""hi all
i will you all to my python learning programme"""
print(str)
print(len(str))
x=type(str)
print(x)
x=str.split()
print(x)
x=str.replace('learning','stding')
print(x)
x=str.lower()
print(x)
x=str.upper()
print(x)
x=str.capitalize()
print(x)